import "dotenv/config";
import { PrismaClient } from "../src/generated/prisma/client";

const prisma = new PrismaClient();

async function main() {
  await prisma.influencer.deleteMany();

  const influencers = [
    {
      name: "Mohammed Al-Qahtani",
      email: "m.qahtani@outlook.sa",
      phone: "+966501112233",
      location: "Saudi Arabia",
      city: "Riyadh",
      sex: "MALE" as const,
      platform: "INSTAGRAM" as const,
      handle: "@mohammedq.fit",
      followers: 870000,
      engagementRate: 4.3,
      niche: "Fitness",
      traits: "face,hook_master,speaking,storytelling",
      ratePerPost: 18000,
      status: "ACTIVE" as const,
    },
    {
      name: "Sara Al-Ghamdi",
      email: "sara.ghamdi@gmail.com",
      phone: "+966502223344",
      location: "Saudi Arabia",
      city: "Jeddah",
      sex: "FEMALE" as const,
      platform: "INSTAGRAM" as const,
      handle: "@sara.fashion.sa",
      followers: 1240000,
      engagementRate: 5.7,
      niche: "Fashion",
      traits: "face,lifestyle,storytelling,trend_setter",
      ratePerPost: 24000,
      status: "ACTIVE" as const,
    },
    {
      name: "Fahad Al-Otaibi",
      email: "fahad.content@gmail.com",
      phone: "+966503334455",
      location: "Saudi Arabia",
      city: "Riyadh",
      sex: "MALE" as const,
      platform: "TIKTOK" as const,
      handle: "@fahadcomedy",
      followers: 2350000,
      engagementRate: 8.1,
      niche: "Lifestyle",
      traits: "face,comedy,hook_master,trend_setter",
      ratePerPost: 35000,
      status: "ACTIVE" as const,
    },
    {
      name: "Nora Al-Mutairi",
      email: "nora.beauty@hotmail.com",
      phone: "+966504445566",
      location: "Saudi Arabia",
      city: "Riyadh",
      sex: "FEMALE" as const,
      platform: "TIKTOK" as const,
      handle: "@nora.beauty",
      followers: 985000,
      engagementRate: 6.4,
      niche: "Beauty",
      traits: "face,educational,review,ugc",
      ratePerPost: 16000,
      status: "ACTIVE" as const,
    },
    {
      name: "Abdullah Al-Zahrani",
      email: "abd.tech@gmail.com",
      phone: "+966505556677",
      location: "Saudi Arabia",
      city: "Dammam",
      sex: "MALE" as const,
      platform: "YOUTUBE" as const,
      handle: "@abdtech.sa",
      followers: 460000,
      engagementRate: 3.9,
      niche: "Tech",
      traits: "speaking,educational,review,voiceover",
      ratePerPost: 12000,
      status: "ACTIVE" as const,
    },
    {
      name: "Lujain Al-Omran",
      email: "lujain.lifestyle@gmail.com",
      phone: "+966506667788",
      location: "Saudi Arabia",
      city: "Jeddah",
      sex: "FEMALE" as const,
      platform: "INSTAGRAM" as const,
      handle: "@lujain.life",
      followers: 1820000,
      engagementRate: 4.8,
      niche: "Lifestyle",
      traits: "face,storytelling,lifestyle,trend_setter",
      ratePerPost: 30000,
      status: "ACTIVE" as const,
    },
    {
      name: "Ahmad Al-Shehri",
      email: "ahmad.travel@gmail.com",
      phone: "+966507778899",
      location: "Saudi Arabia",
      city: "Abha",
      sex: "MALE" as const,
      platform: "YOUTUBE" as const,
      handle: "@ahmadexplores",
      followers: 670000,
      engagementRate: 5.2,
      niche: "Travel",
      traits: "face,storytelling,hook_master,speaking",
      ratePerPost: 14000,
      status: "ACTIVE" as const,
    },
    {
      name: "Reem Al-Dosari",
      email: "reem.food@hotmail.com",
      phone: "+966508889900",
      location: "Saudi Arabia",
      city: "Khobar",
      sex: "FEMALE" as const,
      platform: "TIKTOK" as const,
      handle: "@reemcooks",
      followers: 730000,
      engagementRate: 7.3,
      niche: "Food",
      traits: "face,review,hook_master,ugc",
      ratePerPost: 11000,
      status: "ACTIVE" as const,
    },
    {
      name: "Turki Al-Harbi",
      email: "turki.motiv@gmail.com",
      phone: "+966509990011",
      location: "Saudi Arabia",
      city: "Madinah",
      sex: "MALE" as const,
      platform: "INSTAGRAM" as const,
      handle: "@turki.motivates",
      followers: 540000,
      engagementRate: 6.0,
      niche: "Fitness",
      traits: "speaking,hook_master,storytelling,educational",
      ratePerPost: 9500,
      status: "ACTIVE" as const,
    },
    {
      name: "Dina Al-Shihri",
      email: "dina.fashion@gmail.com",
      phone: "+966500011122",
      location: "Saudi Arabia",
      city: "Jeddah",
      sex: "FEMALE" as const,
      platform: "INSTAGRAM" as const,
      handle: "@dina.closet",
      followers: 1100000,
      engagementRate: 4.6,
      niche: "Fashion",
      traits: "face,ugc,trend_setter,lifestyle",
      ratePerPost: 20000,
      status: "ACTIVE" as const,
    },
    {
      name: "Khalid Al-Rashidi",
      email: "khalid.gaming@gmail.com",
      phone: "+966500122233",
      location: "Saudi Arabia",
      city: "Riyadh",
      sex: "MALE" as const,
      platform: "YOUTUBE" as const,
      handle: "@khalidgames",
      followers: 920000,
      engagementRate: 5.5,
      niche: "Gaming",
      traits: "voiceover,comedy,hook_master,educational",
      ratePerPost: 13500,
      status: "ACTIVE" as const,
    },
    {
      name: "Maha Al-Qahtani",
      email: "maha.wellness@hotmail.com",
      phone: "+966500233344",
      location: "Saudi Arabia",
      city: "Taif",
      sex: "FEMALE" as const,
      platform: "INSTAGRAM" as const,
      handle: "@maha.wellness",
      followers: 310000,
      engagementRate: 7.8,
      niche: "Fitness",
      traits: "face,educational,storytelling,speaking",
      ratePerPost: 7000,
      status: "INACTIVE" as const,
    },
  ];

  for (const data of influencers) {
    await prisma.influencer.create({ data });
  }

  console.log(`Seeded ${influencers.length} Saudi influencers.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
